/*
 * Copyright 2024-2025 NetCracker Technology Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is provided "AS IS", without warranties
 * or conditions of any kind, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.qubership.atp.svp.controllers.constants;

public class ExecutorControllerTestConstants {

    public static final String LOG_COLLECTOR_CONFIGURATION_DEFAULT = "[ {\n"
            + "        \"active\": false,\n"
            + "        \"created\": \"2021-05-13 08:19:28.853\",\n"
            + "        \"createdBy\": null,\n"
            + "        \"id\": \"24d1ea9f-45b3-4256-9a2d-26372ad134b8\",\n"
            + "        \"modified\": null,\n"
            + "        \"modifiedBy\": null,\n"
            + "        \"name\": \"GRAYLOG\",\n"
            + "        \"parameters\": {\n"
            + "            \"filebasedParameters\": {},\n"
            + "            \"fields\": [\n"
            + "                \"context\",\n"
            + "                \"operation_name\",\n"
            + "                \"type\",\n"
            + "                \"payload\",\n"
            + "                \"integration_scenario\",\n"
            + "                \"header\"\n"
            + "            ],\n"
            + "            \"graylogParameters\": {\n"
            + "                \"isRegexp\": false,\n"
            + "                \"filterText\": \"\",\n"
            + "                \"caseSensitive\": false\n"
            + "            },\n"
            + "            \"kuberParameters\": {},\n"
            + "            \"systemNames\": [\n"
            + "                \"GRAYLOG\"\n"
            + "            ]\n"
            + "        },\n"
            + "        \"projectId\": \"323eda51-47b5-414a-951a-27221fa374a2\",\n"
            + "        \"type\": \"GRAYLOG\"\n"
            + "    }, {\n"
            + "        \"active\": false,\n"
            + "        \"created\": \"2021-05-13 08:19:28.853\",\n"
            + "        \"createdBy\": null,\n"
            + "        \"id\": \"24d1ea9f-45b3-4256-9a2d-26372ad134b9\",\n"
            + "        \"modified\": null,\n"
            + "        \"modifiedBy\": null,\n"
            + "        \"name\": \"GRAYLOG\",\n"
            + "        \"parameters\": {\n"
            + "            \"filebasedParameters\": {},\n"
            + "            \"fields\": [\n"
            + "                \"context\",\n"
            + "                \"operation_name\",\n"
            + "                \"type\",\n"
            + "                \"payload\",\n"
            + "                \"integration_scenario\",\n"
            + "                \"header\"\n"
            + "            ],\n"
            + "            \"graylogParameters\": {\n"
            + "                \"isRegexp\": false,\n"
            + "                \"filterText\": \"\",\n"
            + "                \"caseSensitive\": false\n"
            + "            },\n"
            + "            \"kuberParameters\": {},\n"
            + "            \"systemNames\": [\n"
            + "                \"GRAYLOG\"\n"
            + "            ]\n"
            + "        },\n"
            + "        \"projectId\": \"323eda51-47b5-414a-951a-27221fa374a2\",\n"
            + "        \"type\": \"GRAYLOG\"\n"
            + "    }]";

    public static final String LOG_COLLECTOR_REGISTER_SEARCH_RESPONSE_DEFAULT = "{\n"
            + "  \"errorCode\":  %3$s,\n"
            + "  \"errorDetails\": null,\n"
            + "  \"logsLink\": null,\n"
            + "  \"searchId\": \"%1$s\",\n"
            + "  \"status\": \"IN_PROGRESS\",\n"
            + "  \"componentSearchResults\": [\n"
            + "    {\n"
            + "      \"searchId\": \"%1$s\",\n"
            + "      \"errorCode\": null,\n"
            + "      \"errorDetails\": null,\n"
            + "      \"logsLink\": null,\n"
            + "      \"componentSearchId\": \"5e9c3944-71fb-4eba-bf5c-c0b66ccab6b6\",\n"
            + "      \"componentId\": \"%2$s\",\n"
            + "      \"componentName\": \"GRAYLOG\",\n"
            + "      \"componentType\": \"GRAYLOG\",\n"
            + "      \"templateIds\": [],\n"
            + "      \"status\": \"IN_PROGRESS\",\n"
            + "      \"searchPatternType\": \"QUERY\",\n"
            + "      \"searchPattern\": \"type: Response\",\n"
            + "      \"filterText\": \"LC_NO_FILTER\",\n"
            + "      \"searchStrategy\": null,\n"
            + "      \"surroundingLinesQuantity\": null,\n"
            + "      \"systemSearchResults\": [\n"
            + "        {\n"
            + "          \"errorCode\": null,\n"
            + "          \"errorDetails\": null,\n"
            + "          \"logsLink\": null,\n"
            + "          \"systemSearchId\": \"95021744-42df-433f-8e35-15e5eb9ce28b\",\n"
            + "          \"systemName\": \"GRAYLOG\",\n"
            + "          \"status\": \"IN_PROGRESS\",\n"
            + "          \"searchThreadResult\": []\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  ]\n"
            + "}\n";
    public static final String INTEGRATION_LOG_PARAMETER_ERROR_VALUE_OBJECT_REGISTER_SEARCH_DEFAULT_MESSAGE = "Failed "
            + "to register search in LogCollector with request body: LogCollectorSearchRequest"
            + "(projectId=323eda51-47b5-414a-951a-27221fa374a2, environmentId=null, "
            + "configurations=[%s], parameters=LogCollectorSearchRequestParameters"
            + "(rangeType=RELATIVE, timeRange=86400, startDate=null, endDate=null, searchPattern="
            + "(Test_Sales_Order_ID|Test_Customer_ID), searchPatternQuery=context: Test_Sales_Order_ID AND "
            + "integration_scenario: \"[OCS] Modify Add-On Subscription\" AND type:%s, "
            + "searchPatternType=TEXT, searchStrategy=SURROUNDING_LINES, fileTrimmingStrategy=TRIM_BY_SEARCHING_TIME,"
            + " filterText=LC_NO_FILTER, surroundingLinesQuantity=0, surroundingMinutesQuantity=0, "
            + "readOnlyMode=false, searchPerOneDay=false, skipArchivation=true), templates=null, "
            + "requestId=%s, requestTool=atp-svp)";

    public static final String LOG_COLLECTOR_SEARCH_RESULT_DEFAULT = "{\n"
            + "  \"errorCode\": %3$s,\n"
            + "  \"errorDetails\": null,\n"
            + "  \"errors\": [],\n"
            + "  \"logsLink\": null,\n"
            + "  \"searchId\": \"%1$s\",\n"
            + "  \"status\": \"%4$s\",\n"
            + "  \"componentSearchResults\": [\n"
            + "    {\n"
            + "      \"searchId\": \"%1$s\",\n"
            + "      \"errorCode\": null,\n"
            + "      \"errorDetails\": null,\n"
            + "      \"logsLink\": null,\n"
            + "      \"componentSearchId\": \"5e9c3944-71fb-4eba-bf5c-c0b66ccab6b6\",\n"
            + "      \"componentId\": \"%2$s\",\n"
            + "      \"componentName\": \"GRAYLOG\",\n"
            + "      \"componentType\": \"GRAYLOG\",\n"
            + "      \"templateIds\": [],\n"
            + "      \"status\": \"COMPLETED\",\n"
            + "      \"searchPatternType\": \"QUERY\",\n"
            + "      \"searchPattern\": \"type: Response\",\n"
            + "      \"filterText\": \"LC_NO_FILTER\",\n"
            + "      \"searchStrategy\": null,\n"
            + "      \"surroundingLinesQuantity\": null,\n"
            + "      \"systemSearchResults\": [\n"
            + "        {\n"
            + "          \"errorCode\": null,\n"
            + "          \"errorDetails\": null,\n"
            + "          \"logsLink\": \"api/logs/download/Project "
            + "Oman/GRAYLOG/GRAYLOG_95021744-42df-433f-8e35-15e5eb9ce28b_28-05-21-04-09-12.190.csv\",\n"
            + "          \"systemSearchId\": \"95021744-42df-433f-8e35-15e5eb9ce28b\",\n"
            + "          \"systemName\": \"GRAYLOG\",\n"
            + "          \"status\": \"COMPLETED\",\n"
            + "          \"searchThreadResult\": [\n"
            + "            {\n"
            + "              \"foundInDirectory\": null,\n"
            + "              \"logFileName\": \"GRAYLOG_95021744-42df-433f-8e35-15e5eb9ce28b_28-05-21-04-09-12.190"
            + ".csv\",\n"
            + "              \"logsLink\": \"https://localhost"
            + "/streams/600933b573bd9f4ddf8a42ca20/search?rangetype=absolute&fields=operation_name,payload,"
            + "context,integration_scenario,header,type,message&from=2021-05-26T04:09:09.000Z&to=2021-05-28T04:09:09"
            + ".000Z&q=type:20Response\",\n"
            + "              \"messages\": [[\"integration log\"]],\n"
            + "              \"parameters\": {\n"
            + "                \"operation_name\": \"ZDS\",\n"
            + "                \"payload\": \"{\\n  \\\"productOrderItem\\\": [\\n    {\\n      \\\"product\\\": {\\n"
            + "        \\\"productCharacteristic\\\": [\\n          {\\n            \\\"valueType\\\": "
            + "\\\"string\\\",\\n            \\\"name\\\": \\\"thresholdName\\\",\\n            \\\"value\\\": "
            + "\\\"AutoTopupRenew\\\"\\n          },\\n          {\\n            \\\"valueType\\\": \\\"string\\\","
            + "\\n            \\\"name\\\": \\\"thresholdValue\\\",\\n            \\\"value\\\": \\\"\\\"\\n         "
            + " }\\n        ]\\n      },\\n      \\\"action\\\": \\\"replace\\\",\\n      \\\"id\\\": "
            + "\\\"entitlement\\\"\\n    }\\n  ],\\n  \\\"relatedParty\\\": [\\n    {\\n      \\\"id\\\": "
            + "\\\"d8bfd05a-e7d3-4128-ad1e-77122f907f62\\\"\\n    }\\n  ],\\n  \\\"orderTotalPrice\\\": [\\n    {\\n "
            + "     \\\"price\\\": {\\n        \\\"validFor\\\": {\\n          \\\"startDateTime\\\": "
            + "\\\"2021-05-26T09:41:47Z\\\"\\n        },\\n        \\\"taxIncludedAmount\\\": {\\n          "
            + "\\\"value\\\": \\\"3000\\\"\\n        }\\n      }\\n    }\\n  ]\\n}\\n\",\n"
            + "                \"context\": \"/pms/api/backend/translations/v1\",\n"
            + "                \"integration_scenario\": \"Get Product Offering Translations\",\n"
            + "                \"header\": \"GET http://atp-itf-project.dev.somedomain"
            + ".com/mockingbird-transport-rest/pms/api/backend/translations/v1\\\\\\\\n\\\\\\\\nTransfer-Encoding: "
            + "chunked\\\\\\\\nContent-Type: application/json\\\\\\\\nTransfer-Encoding: chunked\\\\\\\\nDate: Fri, "
            + "28 May 2021 00:54:54 GMT\\\\\\\\nSet-Cookie: "
            + "be1211f3e1f5ea043deebdf52d7d5e0b=c9bfa5da71af354c7c4b60c04389d652; path=/; "
            + "HttpOnly\\\\\\\\nCache-control: public\",\n"
            + "                \"type\": \"Response\"\n"
            + "              },\n"
            + "              \"timestamp\": \"2021-05-28T00:53:11.776Z\"\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  ]\n"
            + "}\n";

    public static final String LOG_COLLECTOR_SEARCH_RESULT_WITHOUT_LOGS = "{\n"
            + "\t\"errorCode\": null,\n"
            + "\t\"errorDetails\": null,\n"
            + "\t\"logsLink\": null,\n"
            + "\t\"searchId\": \"%1$s\",\n"
            + "\t\"status\": \"FAILED\",\n"
            + "\t\"componentSearchResults\": [\n"
            + "\t\t{\n"
            + "\t\t\t\"componentId\": \"%2$s\",\n"
            + "\t\t\t\"componentName\": \"GRAYLOG\",\n"
            + "\t\t\t\"componentSearchId\": \"5e9c3944-71fb-4eba-bf5c-c0b66ccab6b6\",\n"
            + "\t\t\t\"componentType\": \"GRAYLOG\",\n"
            + "\t\t\t\"errorCode\": null,\n"
            + "\t\t\t\"errorDetails\": null,\n"
            + "\t\t\t\"filterText\": \"LC_NO_FILTER\",\n"
            + "\t\t\t\"logsLink\": null,\n"
            + "\t\t\t\"searchId\": \"%1$s\",\n"
            + "\t\t\t\"searchPattern\": \"type: Response\",\n"
            + "\t\t\t\"searchPatternType\": \"QUERY\",\n"
            + "\t\t\t\"searchStrategy\": null,\n"
            + "\t\t\t\"status\": \"FAILED\",\n"
            + "\t\t\t\"surroundingLinesQuantity\": null,\n"
            + "\t\t\t\"systemSearchResults\": [\n"
            + "\t\t\t\t{\n"
            + "\t\t\t\t\t\"errorCode\": %3$s,\n"
            + "\t\t\t\t\t\"errorDetails\": null,\n"
            + "\t\t\t\t\t\"logsLink\": \"api/logs/download/Project "
            + "Oman/GRAYLOG/GRAYLOG_95021744-42df-433f-8e35-15e5eb9ce28b_28-05-21-04-09-12.190.csv\",\n"
            + "          \"systemSearchId\": \"95021744-42df-433f-8e35-15e5eb9ce28b\",\n"
            + "\t\t\t\t\t\"searchThreadResult\": [],\n"
            + "\t\t\t\t\t\"systemName\": \"GRAYLOG\",\n"
            + "\t\t\t\t\t\"systemSearchId\": \"95021744-42df-433f-8e35-15e5eb9ce28b\",\n"
            + "\t\t\t\t\t\"status\": \"%4$s\"\n"
            + "\t\t\t\t}\n"
            + "\t\t\t],\n"
            + "\t\t\t\"templateIds\": []\n"
            + "\t\t}\n"
            + "\t]\n"
            + "}";

    public static final String LOG_COLLECTOR_VALUE_OBJECT_DEFAULT = "{\n"
            + "\t\"type\":\"LogCollectorValueObject\",\n"
            + "\t\"hasResults\": true,\n"
            + "\t\"searchResult\": {\n"
            + "\t\t\"errorCode\": %3$s, \n"
            + "\t\t\"errorDetails\": null,\n"
            + "\t\t\"logsLink\": null,\n"
            + "\t\t\"searchId\": \"%1$s\",\n"
            + "\t\t\"status\": \"%4$s\",\n"
            + "\t\t\"componentSearchResults\": [\n"
            + "\t\t\t{\n"
            + "\t\t\t\t\"componentId\": \"%2$s\",\n"
            + "\t\t\t\t\"componentName\": \"GRAYLOG\",\n"
            + "\t\t\t\t\"componentSearchId\": \"5e9c3944-71fb-4eba-bf5c-c0b66ccab6b6\",\n"
            + "\t\t\t\t\"componentType\": \"GRAYLOG\",\n"
            + "\t\t\t\t\"errorCode\": null,\n"
            + "\t\t\t\t\"errorDetails\": null,\n"
            + "\t\t\t\t\"filterText\": \"LC_NO_FILTER\",\n"
            + "\t\t\t\t\"logsLink\": null,\n"
            + "\t\t\t\t\"searchId\": \"%1$s\",\n"
            + "\t\t\t\t\"searchPattern\": \"type: Response\",\n"
            + "\t\t\t\t\"searchPatternType\": \"QUERY\",\n"
            + "\t\t\t\t\"searchStrategy\": null,\n"
            + "\t\t\t\t\"status\": \"COMPLETED\",\n"
            + "\t\t\t\t\"surroundingLinesQuantity\": null,\n"
            + "\t\t\t\t\"systemSearchResults\": [\n"
            + "\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\"errorCode\": null,\n"
            + "\t\t\t\t\t\t\"errorDetails\": null,\n"
            + "\t\t\t\t\t\t\"logsLink\": \"api/logs/download/Project "
            + "Oman/GRAYLOG/GRAYLOG_95021744-42df-433f-8e35-15e5eb9ce28b_28-05-21-04-09-12.190.csv\",\n"
            + "\t\t\t\t\t\t\"searchThreadResult\": [\n"
            + "\t\t\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\t\t\"foundInDirectory\": null,\n"
            + "\t\t\t\t\t\t\t\t\"logFileName\": \"GRAYLOG_95021744-42df-433f-8e35-15e5eb9ce28b_28-05-21-04-09-12.190"
            + ".csv\",\n"
            + "\t\t\t\t\t\t\t\t\"logsLink\": \"https://localhost"
            + "/streams/600933b573bd9f4ddf8a42ca20/search?rangetype=absolute&fields=operation_name,payload,"
            + "context,integration_scenario,header,type,message&from=2021-05-26T04:09:09.000Z&to=2021-05-28T04:09:09"
            + ".000Z&q=type:20Response\",\n"
            + "\t\t\t\t\t\t\t\t\"messages\": [\n"
            + "\t\t\t\t\t\t\t\t\t[\n"
            + "\t\t\t\t\t\t\t\t\t\t\"integration log\"\n"
            + "\t\t\t\t\t\t\t\t\t]\n"
            + "\t\t\t\t\t\t\t\t],\n"
            + "\t\t\t\t\t\t\t\t\"parameters\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"operation_name\": \"ZDS\",\n"
            + "\t\t\t\t\t\t\t\t\t\"payload\": \"{\\n  \\\"productOrderItem\\\": [\\n    {\\n      \\\"product\\\": "
            + "{\\n        \\\"productCharacteristic\\\": [\\n          {\\n            \\\"valueType\\\": "
            + "\\\"string\\\",\\n            \\\"name\\\": \\\"thresholdName\\\",\\n            \\\"value\\\": "
            + "\\\"AutoTopupRenew\\\"\\n          },\\n          {\\n            \\\"valueType\\\": \\\"string\\\","
            + "\\n            \\\"name\\\": \\\"thresholdValue\\\",\\n            \\\"value\\\": \\\"\\\"\\n         "
            + " }\\n        ]\\n      },\\n      \\\"action\\\": \\\"replace\\\",\\n      \\\"id\\\": "
            + "\\\"entitlement\\\"\\n    }\\n  ],\\n  \\\"relatedParty\\\": [\\n    {\\n      \\\"id\\\": "
            + "\\\"d8bfd05a-e7d3-4128-ad1e-77122f907f62\\\"\\n    }\\n  ],\\n  \\\"orderTotalPrice\\\": [\\n    {\\n "
            + "     \\\"price\\\": {\\n        \\\"validFor\\\": {\\n          \\\"startDateTime\\\": "
            + "\\\"2021-05-26T09:41:47Z\\\"\\n        },\\n        \\\"taxIncludedAmount\\\": {\\n          "
            + "\\\"value\\\": \\\"3000\\\"\\n        }\\n      }\\n    }\\n  ]\\n}\\n\",\n"
            + "\t\t\t\t\t\t\t\t\t\"context\": \"/pms/api/backend/translations/v1\",\n"
            + "\t\t\t\t\t\t\t\t\t\"integration_scenario\": \"Get Product Offering Translations\",\n"
            + "\t\t\t\t\t\t\t\t\t\"header\": \"GET http://atp-itf-project.atp-cloud.sodomain"
            + ".com/mockingbird-transport-rest/pms/api/backend/translations/v1\\\\\\\\n\\\\\\\\nTransfer-Encoding: "
            + "chunked\\\\\\\\nContent-Type: application/json\\\\\\\\nTransfer-Encoding: chunked\\\\\\\\nDate: Fri, "
            + "28 May 2021 00:54:54 GMT\\\\\\\\nSet-Cookie: "
            + "be1211f3e1f5ea043deebdf52d7d5e0b=c9bfa5da71af354c7c4b60c04389d652; path=/; "
            + "HttpOnly\\\\\\\\nCache-control: public\",\n"
            + "\t\t\t\t\t\t\t\t\t\"type\": \"Response\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"timestamp\": \"2021-05-28T00:53:11.776Z\",\n"
            + "\t\t\t\t\t\t\t\t\"messageAsSingleString\": \"integration log\\n\"\n"
            + "\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t],\n"
            + "\t\t\t\t\t\t\"status\": \"COMPLETED\",\n"
            + "\t\t\t\t\t\t\"systemName\": \"GRAYLOG\",\n"
            + "\t\t\t\t\t\t\"systemSearchId\": \"95021744-42df-433f-8e35-15e5eb9ce28b\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t],\n"
            + "\t\t\t\t\"templateIds\": [],\n"
            + "\t\t\t\t\"graylog\": true\n"
            + "\t\t\t}\n"
            + "\t\t]\n"
            + "\t}\n"
            + "}";

    public static final String LOG_COLLECTOR_VALUE_OBJECT_WITHOUT_LOGS = "{\n"
            + "\t\"hasResults\": true,\n"
            + "\t\"searchResult\": {\n"
            + "\t\t\"errorCode\": null, \n"
            + "\t\t\"errorDetails\": null,\n"
            + "\t\t\"logsLink\": null,\n"
            + "\t\t\"searchId\": \"%1$s\",\n"
            + "\t\t\"status\": \"FAILED\",\n"
            + "\t\t\"componentSearchResults\": [\n"
            + "\t\t\t{\n"
            + "\t\t\t\t\"componentId\": \"%2$s\",\n"
            + "\t\t\t\t\"componentName\": \"GRAYLOG\",\n"
            + "\t\t\t\t\"componentSearchId\": \"5e9c3944-71fb-4eba-bf5c-c0b66ccab6b6\",\n"
            + "\t\t\t\t\"componentType\": \"GRAYLOG\",\n"
            + "\t\t\t\t\"errorCode\": null,\n"
            + "\t\t\t\t\"errorDetails\": null,\n"
            + "\t\t\t\t\"filterText\": \"LC_NO_FILTER\",\n"
            + "\t\t\t\t\"logsLink\": null,\n"
            + "\t\t\t\t\"searchId\": \"%1$s\",\n"
            + "\t\t\t\t\"searchPattern\": \"type: Response\",\n"
            + "\t\t\t\t\"searchPatternType\": \"QUERY\",\n"
            + "\t\t\t\t\"searchStrategy\": null,\n"
            + "\t\t\t\t\"status\": \"FAILED\",\n"
            + "\t\t\t\t\"surroundingLinesQuantity\": null,\n"
            + "\t\t\t\t\"systemSearchResults\": [\n"
            + "\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\"errorCode\": %3$s,\n"
            + "\t\t\t\t\t\t\"errorDetails\": null,\n"
            + "\t\t\t\t\t\t\"logsLink\": \"api/logs/download/Project "
            + "Oman/GRAYLOG/GRAYLOG_95021744-42df-433f-8e35-15e5eb9ce28b_28-05-21-04-09-12.190.csv\",\n"
            + "\t\t\t\t\t\t\"searchThreadResult\": [],\n"
            + "\t\t\t\t\t\t\"status\": \"%4$s\",\n"
            + "\t\t\t\t\t\t\"systemName\": \"GRAYLOG\",\n"
            + "\t\t\t\t\t\t\"systemSearchId\": \"95021744-42df-433f-8e35-15e5eb9ce28b\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t],\n"
            + "\t\t\t\t\"templateIds\": [],\n"
            + "\t\t\t\t\"graylog\": true\n"
            + "\t\t\t}\n"
            + "\t\t]\n"
            + "\t}\n"
            + "}";

    public static String getLogCollectorResultSearchResponseWithoutLogs(String searchId, String componentId,
                                                                        String errorCode, String searchStatus) {
        return String.format(LOG_COLLECTOR_SEARCH_RESULT_WITHOUT_LOGS, searchId, componentId, errorCode, searchStatus);
    }

    public static String getLogCollectorValueObjectWithoutLogs(String searchId, String componentId, String errorCode,
                                                               String searchStatus) {
        return String.format(LOG_COLLECTOR_VALUE_OBJECT_WITHOUT_LOGS, searchId, componentId, errorCode, searchStatus);
    }

    public static final String POT_SESSION_COMMON_PARAMETERS_DEFAULT = "[\n"
            + "  {\n"
            + "    \"page\": null,\n"
            + "    \"tab\": null,\n"
            + "    \"group\": null,\n"
            + "    \"parameterConfig\": {\n"
            + "      \"name\": \"Test none\",\n"
            + "      \"displayType\": \"PARAM\",\n"
            + "      \"dataSource\": {\n"
            + "        \"system\": \"Business Solution\",\n"
            + "        \"connection\": \"DB\",\n"
            + "        \"engineType\": \"SQL\",\n"
            + "        \"script\": \"\",\n"
            + "        \"settings\": [\n"
            + "          {\n"
            + "            \"query\": null,\n"
            + "            \"queryParams\": {},\n"
            + "            \"requestType\": \"GET\",\n"
            + "            \"body\": \"\",\n"
            + "            \"urlEncodedBody\": null,\n"
            + "            \"headers\": {}\n"
            + "          }\n"
            + "        ]\n"
            + "      },\n"
            + "      \"logsSource\": {\n"
            + "        \"components\": null,\n"
            + "        \"graylogSearchText\": null,\n"
            + "        \"fileBasedSearchText\": null\n"
            + "      },\n"
            + "      \"er\": {\n"
            + "        \"type\": \"NONE\",\n"
            + "        \"value\": \"\",\n"
            + "        \"tableValidations\": [],\n"
            + "        \"dataSource\": {\n"
            + "          \"system\": \"\",\n"
            + "          \"connection\": \"\",\n"
            + "          \"engineType\": null,\n"
            + "          \"script\": \"\",\n"
            + "          \"settings\": [\n"
            + "            {\n"
            + "              \"query\": null,\n"
            + "              \"queryParams\": {},\n"
            + "              \"requestType\": \"GET\",\n"
            + "              \"body\": \"\",\n"
            + "              \"urlEncodedBody\": null,\n"
            + "              \"headers\": {}\n"
            + "            }\n"
            + "          ]\n"
            + "        },\n"
            + "        \"tableValidationSettings\": { \"keyColumns\": [], \"groupingColumns\": [] },\n"
            + "        \"bulkValidatorValidation\": null\n"
            + "      },\n"
            + "      \"additionalSources\": [],\n"
            + "      \"isPreconfigured\": false,\n"
            + "      \"component\": null\n"
            + "    },\n"
            + "    \"isSynchronousLoading\": false,\n"
            + "    \"er\": null,\n"
            + "    \"arValues\": [],\n"
            + "    \"validationInfo\": null,\n"
            + "    \"logsLink\": null,\n"
            + "    \"name\": \"Test none\",\n"
            + "    \"path\": \"null_null_null_Test none\",\n"
            + "    \"errors\": \"\",\n"
            + "    \"componentName\": null\n"
            + "  }\n"
            + "]";

    public static final String BV_TEST_RUN_CREATION_RESPONSE_DEFAULT = "{\n"
            + "    \"trId\": \"46fec0ec-f984-4fc8-b842-8b2564c42a64\",\n"
            + "    \"context\": {\n"
            + "        \"inputParameters\": [],\n"
            + "        \"values\": [\n"
            + "            {\n"
            + "                \"internalId\": \"-1016660\",\n"
            + "                \"externalId\": \"5a270aaa-ef4c-48e5-880f-66a1bcb3a5a1\",\n"
            + "                \"dataType\": \"SIMPLE\",\n"
            + "                \"name\": \"Request\",\n"
            + "                \"timeStamp\": \"2021-05-28T07:13:01.000+0000\",\n"
            + "                \"contentType\": \"JSON\",\n"
            + "                \"content\": "
            +
            "\"ewoJInByb2R1Y3RPcmRlckl0ZW0iOiBbCgkJewoJCQkicHJvZHVjdCI6IHsKCQkJCSJwcm9kdWN0Q2hhcmFjdGVyaXN0aWMiOiBbCgkJCQkJewoJCQkJCQkidmFsdWVUeXBlIjogInN0cmluZyIsCgkJCQkJCSJuYW1lIjogInRocmVzaG9sZE5hbWUiLAoJCQkJCQkidmFsdWUiOiAiQXV0b1RvcHVwUmVuZXciCgkJCQkJfSwKCQkJCQl7CgkJCQkJCSJ2YWx1ZVR5cGUiOiAic3RyaW5nIiwKCQkJCQkJIm5hbWUiOiAidGhyZXNob2xkVmFsdWUiLAoJCQkJCQkidmFsdWUiOiAiIgoJCQkJCX0KCQkJCV0KCQkJfSwKCQkJImFjdGlvbiI6ICJyZXBsYWNlIiwKCQkJImlkIjogImVudGl0bGVtZW50IgoJCX0KCV0sCgkicmVsYXRlZFBhcnR5IjogWwoJCXsKCQkJImlkIjogImQ4YmZkMDVhLWU3ZDMtNDEyOC1hZDFlLTc3MTIyZjkwN2Y2MiIKCQl9CgldLAoJIm9yZGVyVG90YWxQcmljZSI6IFsKCQl7CgkJCSJwcmljZSI6IHsKCQkJCSJ2YWxpZEZvciI6IHsKCQkJCQkic3RhcnREYXRlVGltZSI6ICIyMDIxLTA1LTI2VDA5OjQxOjQ3WiIKCQkJCX0sCgkJCQkidGF4SW5jbHVkZWRBbW91bnQiOiB7CgkJCQkJInZhbHVlIjogIjMwMDAiCgkJCQl9CgkJCX0KCQl9CgldCn0=\",\n"
            + "                \"childs\": [],\n"
            + "                \"orderNum\": 1\n"
            + "            }\n"
            + "        ],\n"
            + "        \"dataSource\": [],\n"
            + "        \"usedSources\": [],\n"
            + "        \"parameterStatuses\": null,\n"
            + "        \"buildInfo\": null,\n"
            + "        \"readObjects\": [],\n"
            + "        \"errors\": [],\n"
            + "        \"rules\": [],\n"
            + "        \"oldProcessContext\": false\n"
            + "    },\n"
            + "    \"created\": null,\n"
            + "    \"tcId\": \"fc0f5322-2b17-4dde-a8b3-633ee5fdbd6c\",\n"
            + "    \"trStatus\": null,\n"
            + "    \"run\": null,\n"
            + "    \"validationContext\": null,\n"
            + "    \"summaryValidationResult\": null,\n"
            + "    \"contextAsString\":\"{\\\"inputParameters\\\":[],"
            + "\\\"values\\\":[{\\\"internalId\\\":\\\"-1016660\\\","
            + "\\\"externalId\\\":\\\"5a270aaa-ef4c-48e5-880f-66a1bcb3a5a1\\\",\\\"dataType\\\":\\\"SIMPLE\\\","
            + "\\\"name\\\":\\\"Request\\\",\\\"timeStamp\\\":\\\"May 28, 2021 7:13:01 AM\\\","
            + "\\\"contentType\\\":\\\"JSON\\\","
            + "\\\"content"
            +
            "\\\":\\\"ewoJInByb2R1Y3RPcmRlckl0ZW0iOiBbCgkJewoJCQkicHJvZHVjdCI6IHsKCQkJCSJwcm9kdWN0Q2hhcmFjdGVyaXN0aWMiOiBbCgkJCQkJewoJCQkJCQkidmFsdWVUeXBlIjogInN0cmluZyIsCgkJCQkJCSJuYW1lIjogInRocmVzaG9sZE5hbWUiLAoJCQkJCQkidmFsdWUiOiAiQXV0b1RvcHVwUmVuZXciCgkJCQkJfSwKCQkJCQl7CgkJCQkJCSJ2YWx1ZVR5cGUiOiAic3RyaW5nIiwKCQkJCQkJIm5hbWUiOiAidGhyZXNob2xkVmFsdWUiLAoJCQkJCQkidmFsdWUiOiAiIgoJCQkJCX0KCQkJCV0KCQkJfSwKCQkJImFjdGlvbiI6ICJyZXBsYWNlIiwKCQkJImlkIjogImVudGl0bGVtZW50IgoJCX0KCV0sCgkicmVsYXRlZFBhcnR5IjogWwoJCXsKCQkJImlkIjogImQ4YmZkMDVhLWU3ZDMtNDEyOC1hZDFlLTc3MTIyZjkwN2Y2MiIKCQl9CgldLAoJIm9yZGVyVG90YWxQcmljZSI6IFsKCQl7CgkJCSJwcmljZSI6IHsKCQkJCSJ2YWxpZEZvciI6IHsKCQkJCQkic3RhcnREYXRlVGltZSI6ICIyMDIxLTA1LTI2VDA5OjQxOjQ3WiIKCQkJCX0sCgkJCQkidGF4SW5jbHVkZWRBbW91bnQiOiB7CgkJCQkJInZhbHVlIjogIjMwMDAiCgkJCQl9CgkJCX0KCQl9CgldCn0\"\n"
            + "}";

    public static final String BV_COMPARING_RESPONSE_DEFAULT = "[\n"
            + "    {\n"
            + "        \"statusCode\": 10000,\n"
            + "        \"tcName\": \"[E2E-MODIFY-12][OCS] Modify Add-On Subscription - remove auto payment\",\n"
            + "        \"compareResult\": \"IDENTICAL\",\n"
            + "        \"trDate\": \"2021-05-28 07:42:26.61\",\n"
            + "        \"trId\": \"662baa55-76e3-4d5a-8270-41f790da99e6\",\n"
            + "        \"resultLink\": \"validation?trid=662baa55-76e3-4d5a-8270-41f790da99e6\",\n"
            + "        \"steps\": [\n"
            + "            {\n"
            + "                \"stepName\": \"Request\",\n"
            + "                \"compareResult\": \"IDENTICAL\"\n"
            + "            }\n"
            + "        ]\n"
            + "    }\n"
            + "]";

    public static final String INTEGRATION_LOG_POT_SESSION_PARAMETER_WITH_VALIDATION_BEFORE_PROCESSING = "{\n"
            + "  \"page\": \"%1$s\",\n"
            + "  \"tab\": \"OCS\",\n"
            + "  \"group\": \"Integration message\",\n"
            + "  \"parameterConfig\": {\n"
            + "    \"name\": \"[OCS] Modify Add-On Subscription (Request)\",\n"
            + "    \"displayType\": \"INTEGRATION_LOG\",\n"
            + "    \"dataSource\": {\n"
            + "      \"system\": \"GRAYLOG\",\n"
            + "      \"connection\": \"HTTP\",\n"
            + "      \"engineType\": \"LOG_COLLECTOR\",\n"
            + "      \"script\": \"\",\n"
            + "      \"settings\": [\n"
            + "        {\n"
            + "          \"className\": \"LogCollectorSettings\","
            + "          \"configurations\": [\"%2$s\"],\n"
            + "          \"parameters\": {\n"
            + "            \"searchText\": \"(Test_Sales_Order_ID|Test_Customer_ID)\",\n"
            + "            \"graylogSearchText\": \"context: Test_Sales_Order_ID AND integration_scenario: \\\"[OCS] "
            + "Modify Add-On Subscription\\\" AND type:Request\",\n"
            + "            \"lines\": 0,\n"
            + "            \"minutes\": 0,\n"
            + "            \"query\": null,\n"
            + "            \"readOnlyMode\": false,\n"
            + "            \"searchPerOneDay\": false,\n"
            + "            \"searchStrategy\": \"SURROUNDING_LINES\",\n"
            + "            \"previewParameters\": [\n"
            + "              \"operation_name\",\n"
            + "              \"payload\",\n"
            + "              \"integration_scenario\",\n"
            + "              \"header\",\n"
            + "              \"type\"\n"
            + "            ],\n"
            + "            \"isLogMessageColumnShowed\": false,\n"
            + "            \"regexp\": false\n"
            + "          },\n"
            + "          \"searchPeriod\": {\n"
            + "            \"searchType\": \"RELATIVE\",\n"
            + "            \"dateStart\": null,\n"
            + "            \"dateEnd\": null,\n"
            + "            \"timeRange\": 86400\n"
            + "          }\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    \"logsSource\": {\n"
            + "      \"components\": null,\n"
            + "      \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "      \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "    },\n"
            + "    \"er\": {\n"
            + "      \"type\": \"BV_LINK\",\n"
            + "      \"value\": null,\n"
            + "      \"tableValidations\": [],\n"
            + "      \"dataSource\": {\n"
            + "        \"system\": \"\",\n"
            + "        \"connection\": \"\",\n"
            + "        \"engineType\": null,\n"
            + "        \"script\": \"\",\n"
            + "        \"settings\": [\n"
            + "          {\n"
            + "            \"className\": \"LogCollectorSettings\","
            + "            \"configurations\": [],\n"
            + "            \"parameters\": {\n"
            + "              \"searchText\": null,\n"
            + "              \"graylogSearchText\": null,\n"
            + "              \"lines\": 0,\n"
            + "              \"minutes\": 0,\n"
            + "              \"query\": null,\n"
            + "              \"readOnlyMode\": false,\n"
            + "              \"searchPerOneDay\": false,\n"
            + "              \"searchStrategy\": null,\n"
            + "              \"previewParameters\": null,\n"
            + "              \"isLogMessageColumnShowed\": true,\n"
            + "              \"regexp\": false\n"
            + "            },\n"
            + "            \"searchPeriod\": null\n"
            + "          }\n"
            + "        ]\n"
            + "      },\n"
            + "      \"tableValidationSettings\": { \"keyColumns\": [], \"groupingColumns\": [] },\n"
            + "      \"bulkValidatorValidation\": {\n"
            + "        \"validationColumn\": \"\",\n"
            + "        \"validationObjectName\": \"\",\n"
            + "        \"isManualValidation\": false,\n"
            + "        \"validationItem\": [\n"
            + "          { \"validationColumn\": \"payload\", \"validationObjectName\": \"Request\" }\n"
            + "        ],\n"
            + "        \"testCaseIds\": [\"fc0f5322-2b17-4dde-a8b3-633ee5fdbd6c\"]\n"
            + "      }\n"
            + "    },\n"
            + "    \"additionalSources\": [],\n"
            + "    \"isPreconfigured\": false,\n"
            + "    \"component\": null\n"
            + "  },\n"
            + "  \"isSynchronousLoading\": %3$s,\n"
            + "  \"er\": null,\n"
            + "  \"bvLink\": null,\n"
            + "  \"name\": \"[OCS] Modify Add-On Subscription (Request)\",\n"
            + "  \"path\": \"Integration_OCS_Integration message_[OCS] Modify Add-On Subscription (Request)\",\n"
            + "  \"errors\": \"\",\n"
            + "  \"componentName\": null\n"
            + "}\n";

    public static final String LOG_COLLECTOR_ERROR_RESPONSE_BODY_DEFAULT = "{\n"
            + "            \"timestamp\": \"2021-07-28T08:53:12.168+0000\",\n"
            + "                \"status\": 500,\n"
            + "                \"error\": \"Internal Server Error\",\n"
            + "                \"message\": \"%s\",\n"
            + "                \"path\": \"%s\"\n"
            + "        }";

    public static final String INTEGRATION_LOG_POT_SESSION_PARAMETER_WITHOUT_VALIDATION_BEFORE_PROCESSING = "{\n"
            + "  \"page\": \"%1$s\",\n"
            + "  \"tab\": \"OCS\",\n"
            + "  \"group\": \"Integration message\",\n"
            + "  \"parameterConfig\": {\n"
            + "    \"name\": \"[OCS] Modify Add-On Subscription (Response)\",\n"
            + "    \"displayType\": \"INTEGRATION_LOG\",\n"
            + "    \"dataSource\": {\n"
            + "      \"system\": \"GRAYLOG\",\n"
            + "      \"connection\": \"HTTP\",\n"
            + "      \"engineType\": \"LOG_COLLECTOR\",\n"
            + "      \"script\": \"\",\n"
            + "      \"settings\": [\n"
            + "        {\n"
            + "          \"className\": \"LogCollectorSettings\","
            + "          \"configurations\": [\"%2$s\"],\n"
            + "          \"parameters\": {\n"
            + "            \"searchText\": \"(Test_Sales_Order_ID|Test_Customer_ID)\",\n"
            + "            \"graylogSearchText\": \"context: Test_Sales_Order_ID AND integration_scenario: \\\"[OCS] "
            + "Modify Add-On Subscription\\\" AND type:Response\",\n"
            + "            \"lines\": 0,\n"
            + "            \"minutes\": 0,\n"
            + "            \"query\": null,\n"
            + "            \"readOnlyMode\": false,\n"
            + "            \"searchPerOneDay\": false,\n"
            + "            \"searchStrategy\": \"SURROUNDING_LINES\",\n"
            + "            \"previewParameters\": [\n"
            + "              \"operation_name\",\n"
            + "              \"payload\",\n"
            + "              \"integration_scenario\",\n"
            + "              \"header\",\n"
            + "              \"type\"\n"
            + "            ],\n"
            + "            \"isLogMessageColumnShowed\": false,\n"
            + "            \"regexp\": false\n"
            + "          },\n"
            + "          \"searchPeriod\": {\n"
            + "            \"searchType\": \"RELATIVE\",\n"
            + "            \"dateStart\": null,\n"
            + "            \"dateEnd\": null,\n"
            + "            \"timeRange\": 86400\n"
            + "          }\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    \"logsSource\": {\n"
            + "      \"components\": null,\n"
            + "      \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "      \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "    },\n"
            + "    \"er\": {\n"
            + "      \"type\": \"NONE\",\n"
            + "      \"value\": null,\n"
            + "      \"tableValidations\": [],\n"
            + "      \"dataSource\": {\n"
            + "        \"system\": \"\",\n"
            + "        \"connection\": \"\",\n"
            + "        \"engineType\": null,\n"
            + "        \"script\": \"\",\n"
            + "        \"settings\": [\n"
            + "          {\n"
            + "            \"className\": \"LogCollectorSettings\","
            + "            \"configurations\": [],\n"
            + "            \"parameters\": {\n"
            + "              \"searchText\": null,\n"
            + "              \"graylogSearchText\": null,\n"
            + "              \"lines\": 0,\n"
            + "              \"minutes\": 0,\n"
            + "              \"query\": null,\n"
            + "              \"readOnlyMode\": false,\n"
            + "              \"searchPerOneDay\": false,\n"
            + "              \"searchStrategy\": null,\n"
            + "              \"previewParameters\": null,\n"
            + "              \"isLogMessageColumnShowed\": true,\n"
            + "              \"regexp\": false\n"
            + "            },\n"
            + "            \"searchPeriod\": null\n"
            + "          }\n"
            + "        ]\n"
            + "      },\n"
            + "      \"tableValidationSettings\": { \"keyColumns\": [], \"groupingColumns\": [] },\n"
            + "      \"bulkValidatorValidation\": {\n"
            + "        \"validationColumn\": \"\",\n"
            + "        \"validationObjectName\": \"\",\n"
            + "        \"isManualValidation\": false,\n"
            + "        \"validationItem\": null,\n"
            + "        \"testCaseIds\": []\n"
            + "      }\n"
            + "    },\n"
            + "    \"additionalSources\": [],\n"
            + "    \"isPreconfigured\": false,\n"
            + "    \"component\": null\n"
            + "  },\n"
            + "  \"isSynchronousLoading\": false,\n"
            + "  \"er\": null,\n"
            + "  \"arValues\": [],\n"
            + "  \"validationInfo\": {\n"
            + "    \"type\": \"ValidationInfo\",\n"
            + "    \"status\": null,\n"
            + "    \"errorDescription\": null\n"
            + "  },\n"
            + "  \"bvLink\": null,\n"
            + "  \"name\": \"[OCS] Modify Add-On Subscription (Response)\",\n"
            + "  \"path\": \"Integration_OCS_Integration message_[OCS] Modify Add-On Subscription (Response)\",\n"
            + "  \"errors\": \"\",\n"
            + "  \"componentName\": null\n"
            + "}\n";

    public static String getLogCollectorResultSearchResponseDefault(String searchId, String componentId,
                                                                    String errorCode, String searchStatus) {
        return String.format(LOG_COLLECTOR_SEARCH_RESULT_DEFAULT, searchId, componentId, errorCode, searchStatus);
    }

    public static String getLogCollectorValueObjectDefault(String searchId, String componentId, String errorCode,
                                                           String searchStatus) {
        return String.format(LOG_COLLECTOR_VALUE_OBJECT_DEFAULT, searchId, componentId, errorCode, searchStatus);
    }

    public static final String LOG_COLLECTOR_PARAMETER_VALIDATION_INFO_DEFAULT = "{\n"
            + "\t\"type\":\"IntegrationLogsValidationInfo\",\n"
            + "  \"status\": \"PASSED\",\n"
            + "  \"errorDescription\": null,\n"
            + "  \"graylogTableValidations\": {\n"
            + "    \"diffs\": [],\n"
            + "    \"bvTestRunsInfo\": {\n"
            + "      \"0\": [\n"
            + "        {\n"
            + "          \"testCaseName\": \"[E2E-MODIFY-12][OCS] Modify Add-On Subscription - remove auto "
            + "payment\",\n"
            + "          \"testRunLink\": \"http://atp-bv:8080"
            + "/project/323eda51-47b5-414a-951a-27221fa374a2/bvt/validation?trid=662baa55-76e3-4d5a-8270"
            + "-41f790da99e6\",\n"
            + "          \"validationStatus\": \"PASSED\"\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  },\n"
            + "  \"fileBasedTableValidations\": null\n"
            + "}\n";

    public static final String PARAM_TYPED_PARAMETER_DEFAULT = "{\n"
            + "  \"page\": \"SalesOrderInformation\",\n"
            + "  \"tab\": \"Sales Order\",\n"
            + "  \"group\": \"SO\",\n"
            + "  \"parameterConfig\": {\n"
            + "    \"name\": \"Sales Order\",\n"
            + "    \"displayType\": \"PARAM\",\n"
            + "    \"dataSource\": {\n"
            + "      \"system\": \"Business Solution\",\n"
            + "      \"connection\": \"DB\",\n"
            + "      \"engineType\": \"SQL\",\n"
            + "      \"script\": \"\",\n"
            + "      \"settings\": []\n"
            + "    },\n"
            + "    \"logsSource\": {\n"
            + "      \"components\": [],\n"
            + "      \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "      \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "    },\n"
            + "    \"er\": {\n"
            + "      \"type\": \"PLAIN\",\n"
            + "      \"value\": \"9158075759713577069\",\n"
            + "      \"tableValidations\": [],\n"
            + "      \"dataSource\": {\n"
            + "        \"system\": \"\",\n"
            + "        \"connection\": \"\",\n"
            + "        \"engineType\": null,\n"
            + "        \"script\": \"\",\n"
            + "        \"settings\": []\n"
            + "      },\n"
            + "      \"tableValidationSettings\": { \"keyColumns\": [], \"groupingColumns\": [] },\n"
            + "      \"bulkValidatorValidation\": {\n"
            + "        \"validationColumn\": \"\",\n"
            + "        \"validationObjectName\": \"\",\n"
            + "        \"isManualValidation\": false,\n"
            + "        \"validationItem\": [\n"
            + "          { \"validationColumn\": \"\", \"validationObjectName\": \"\" }\n"
            + "        ],\n"
            + "        \"testCaseIds\": []\n"
            + "      }\n"
            + "    },\n"
            + "    \"additionalSources\": [],\n"
            + "    \"isPreconfigured\": false,\n"
            + "    \"component\": null\n"
            + "  },\n"
            + "  \"isSynchronousLoading\": false,\n"
            + "  \"er\": null,\n"
            + "  \"arValues\": [],\n"
            + "  \"validationInfo\": { \"status\": \"FAILED\", \"errorDescription\": null },\n"
            + "  \"bvLink\": null,\n"
            + "  \"errors\": \"\",\n"
            + "  \"componentName\": null,\n"
            + "  \"name\": \"Sales Order\",\n"
            + "  \"path\": \"SalesOrderInformation_Sales Order_SO_Sales Order\"\n"
            + "}\n";

    public static final String LINK_TYPED_PARAMETER_DEFAULT = "{\n"
            + "  \"page\": \"SalesOrderInformation\",\n"
            + "  \"tab\": \"Sales Order\",\n"
            + "  \"group\": \"SO\",\n"
            + "  \"parameterConfig\": {\n"
            + "    \"name\": \"Sales Order Link\",\n"
            + "    \"displayType\": \"LINK\",\n"
            + "    \"dataSource\": {\n"
            + "      \"system\": \"Business Solution\",\n"
            + "      \"connection\": \"DB\",\n"
            + "      \"engineType\": \"SQL\",\n"
            + "      \"script\": \"\",\n"
            + "      \"settings\": []\n"
            + "    },\n"
            + "    \"logsSource\": {\n"
            + "      \"components\": [],\n"
            + "      \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "      \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "    },\n"
            + "    \"er\": {\n"
            + "      \"type\": \"PLAIN\",\n"
            + "      \"value\": \"9158075759713577069\",\n"
            + "      \"tableValidations\": [],\n"
            + "      \"dataSource\": {\n"
            + "        \"system\": \"\",\n"
            + "        \"connection\": \"\",\n"
            + "        \"engineType\": null,\n"
            + "        \"script\": \"\",\n"
            + "        \"settings\": []\n"
            + "      },\n"
            + "      \"tableValidationSettings\": { \"keyColumns\": [], \"groupingColumns\": [] },\n"
            + "      \"bulkValidatorValidation\": {\n"
            + "        \"validationColumn\": \"\",\n"
            + "        \"validationObjectName\": \"\",\n"
            + "        \"isManualValidation\": false,\n"
            + "        \"validationItem\": [\n"
            + "          { \"validationColumn\": \"\", \"validationObjectName\": \"\" }\n"
            + "        ],\n"
            + "        \"testCaseIds\": []\n"
            + "      }\n"
            + "    },\n"
            + "    \"additionalSources\": [],\n"
            + "    \"isPreconfigured\": false,\n"
            + "    \"component\": null\n"
            + "  },\n"
            + "  \"isSynchronousLoading\": false,\n"
            + "  \"er\": null,\n"
            + "  \"arValues\": [],\n"
            + "  \"validationInfo\": { \"status\": \"FAILED\", \"errorDescription\": null },\n"
            + "  \"bvLink\": null,\n"
            + "  \"errors\": \"\",\n"
            + "  \"componentName\": null,\n"
            + "  \"name\": \"Sales Order Link\",\n"
            + "  \"path\": \"SalesOrderInformation_Sales Order_SO_Sales Order Link\"\n"
            + "}\n";

    public static final String PARAM_TYPED_SYNCHRONOUS_PARAMETER_DEFAULT = "{\n"
            + "\t\"page\": \"%1$s\",\n"
            + "\t\"tab\": \"rest\",\n"
            + "\t\"group\": \"test\",\n"
            + "\t\"parameterConfig\": {\n"
            + "\t\t\"name\": \"%2$s\",\n"
            + "\t\t\"displayType\": \"PARAM\",\n"
            + "\t\t\"dataSource\": {\n"
            + "\t\t\t\"system\": \"Business Solution\",\n"
            + "\t\t\t\"connection\": \"DB\",\n"
            + "\t\t\t\"engineType\": \"SQL\",\n"
            + "\t\t\t\"script\": \"\",\n"
            + "\t\t\t\"settings\": [\n"
            + "\t\t\t\t{\n"
            + "\t\t\t\t\t\"className\": \"HttpSettings\",\n"
            + "\t\t\t\t\t\"query\": \"\",\n"
            + "\t\t\t\t\t\"queryParams\": {},\n"
            + "\t\t\t\t\t\"requestType\": \"GET\",\n"
            + "\t\t\t\t\t\"body\": \"\",\n"
            + "\t\t\t\t\t\"urlEncodedBody\": {},\n"
            + "\t\t\t\t\t\"headers\": {}\n"
            + "\t\t\t\t},\n"
            + "\t\t\t\t{\n"
            + "\t\t\t\t\t\"className\": \"JsonParseSettings\",\n"
            + "\t\t\t\t\t\"jsonViewType\": \"RAW\",\n"
            + "\t\t\t\t\t\"jsonPath\": \"\",\n"
            + "\t\t\t\t\t\"groupNameDivider\": \"||\",\n"
            + "\t\t\t\t\t\"mockJsonScript\": \"\",\n"
            + "\t\t\t\t\t\"columnsData\": [\n"
            + "\t\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\t\"header\": \"\",\n"
            + "\t\t\t\t\t\t\t\"jsonPath\": \"\",\n"
            + "\t\t\t\t\t\t\t\"groupingJsonPaths\": []\n"
            + "\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t],\n"
            + "\t\t\t\t\t\"hierarchyNodeNames\": {\n"
            + "\t\t\t\t\t\t\"id\": \"\",\n"
            + "\t\t\t\t\t\t\"rootId\": \"\",\n"
            + "\t\t\t\t\t\t\"parentId\": \"\"\n"
            + "\t\t\t\t\t},\n"
            + "\t\t\t\t\t\"hierarchyTreeObjectNodeNames\": []\n"
            + "\t\t\t\t},\n"
            + "\t\t\t\t{\n"
            + "\t\t\t\t\t\"className\": \"LogCollectorSettings\",\n"
            + "\t\t\t\t\t\"configurations\": [],\n"
            + "\t\t\t\t\t\"parameters\": {\n"
            + "\t\t\t\t\t\t\"searchText\": null,\n"
            + "\t\t\t\t\t\t\"graylogSearchText\": null,\n"
            + "\t\t\t\t\t\t\"lines\": 0,\n"
            + "\t\t\t\t\t\t\"minutes\": 0,\n"
            + "\t\t\t\t\t\t\"query\": null,\n"
            + "\t\t\t\t\t\t\"readOnlyMode\": false,\n"
            + "\t\t\t\t\t\t\"searchPerOneDay\": false,\n"
            + "\t\t\t\t\t\t\"searchStrategy\": null,\n"
            + "\t\t\t\t\t\t\"previewParameters\": null,\n"
            + "\t\t\t\t\t\t\"isLogMessageColumnShowed\": true,\n"
            + "\t\t\t\t\t\t\"regexp\": false\n"
            + "\t\t\t\t\t},\n"
            + "\t\t\t\t\t\"searchPeriod\": null\n"
            + "\t\t\t\t}\n"
            + "\t\t\t]\n"
            + "\t\t},\n"
            + "\t\t\"logsSource\": {\n"
            + "\t\t\t\"components\": [],\n"
            + "\t\t\t\"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "\t\t\t\"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "\t\t},\n"
            + "\t\t\"er\": {\n"
            + "\t\t\t\"type\": \"NONE\",\n"
            + "\t\t\t\"value\": null,\n"
            + "\t\t\t\"tableValidations\": [],\n"
            + "\t\t\t\"dataSource\": {\n"
            + "\t\t\t\t\"system\": \"\",\n"
            + "\t\t\t\t\"connection\": \"\",\n"
            + "\t\t\t\t\"engineType\": null,\n"
            + "\t\t\t\t\"script\": \"\",\n"
            + "\t\t\t\t\"settings\": [\n"
            + "\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\"className\": \"HttpSettings\",\n"
            + "\t\t\t\t\t\t\"query\": \"\",\n"
            + "\t\t\t\t\t\t\"queryParams\": {},\n"
            + "\t\t\t\t\t\t\"requestType\": \"GET\",\n"
            + "\t\t\t\t\t\t\"body\": \"\",\n"
            + "\t\t\t\t\t\t\"urlEncodedBody\": {},\n"
            + "\t\t\t\t\t\t\"headers\": {}\n"
            + "\t\t\t\t\t},\n"
            + "\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\"className\": \"JsonParseSettings\",\n"
            + "\t\t\t\t\t\t\"jsonViewType\": \"RAW\",\n"
            + "\t\t\t\t\t\t\"jsonPath\": \"\",\n"
            + "\t\t\t\t\t\t\"groupNameDivider\": \"||\",\n"
            + "\t\t\t\t\t\t\"mockJsonScript\": \"\",\n"
            + "\t\t\t\t\t\t\"columnsData\": [\n"
            + "\t\t\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\t\t\"header\": \"\",\n"
            + "\t\t\t\t\t\t\t\t\"jsonPath\": \"\",\n"
            + "\t\t\t\t\t\t\t\t\"groupingJsonPaths\": []\n"
            + "\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t],\n"
            + "\t\t\t\t\t\t\"hierarchyNodeNames\": {\n"
            + "\t\t\t\t\t\t\t\"id\": \"\",\n"
            + "\t\t\t\t\t\t\t\"rootId\": \"\",\n"
            + "\t\t\t\t\t\t\t\"parentId\": \"\"\n"
            + "\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\"hierarchyTreeObjectNodeNames\": []\n"
            + "\t\t\t\t\t},\n"
            + "\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\"className\": \"LogCollectorSettings\",\n"
            + "\t\t\t\t\t\t\"configurations\": [],\n"
            + "\t\t\t\t\t\t\"parameters\": {\n"
            + "\t\t\t\t\t\t\t\"searchText\": null,\n"
            + "\t\t\t\t\t\t\t\"graylogSearchText\": null,\n"
            + "\t\t\t\t\t\t\t\"lines\": 0,\n"
            + "\t\t\t\t\t\t\t\"minutes\": 0,\n"
            + "\t\t\t\t\t\t\t\"query\": null,\n"
            + "\t\t\t\t\t\t\t\"readOnlyMode\": false,\n"
            + "\t\t\t\t\t\t\t\"searchPerOneDay\": false,\n"
            + "\t\t\t\t\t\t\t\"searchStrategy\": null,\n"
            + "\t\t\t\t\t\t\t\"previewParameters\": null,\n"
            + "\t\t\t\t\t\t\t\"isLogMessageColumnShowed\": true,\n"
            + "\t\t\t\t\t\t\t\"regexp\": false\n"
            + "\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\"searchPeriod\": null\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t]\n"
            + "\t\t\t},\n"
            + "\t\t\t\"tableValidationSettings\": {\n"
            + "\t\t\t\t\"keyColumns\": [],\n"
            + "\t\t\t\t\"groupingColumns\": []\n"
            + "\t\t\t},\n"
            + "\t\t\t\"bulkValidatorValidation\": {\n"
            + "\t\t\t\t\"validationColumn\": \"\",\n"
            + "\t\t\t\t\"validationObjectName\": \"\",\n"
            + "\t\t\t\t\"isManualValidation\": false,\n"
            + "\t\t\t\t\"validationItem\": [\n"
            + "\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\"validationColumn\": \"\",\n"
            + "\t\t\t\t\t\t\"validationObjectName\": \"\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t],\n"
            + "\t\t\t\t\"testCaseIds\": []\n"
            + "\t\t\t}\n"
            + "\t\t},\n"
            + "\t\t\"additionalSources\": [],\n"
            + "\t\t\"isPreconfigured\": false,\n"
            + "\t\t\"component\": null\n"
            + "\t},\n"
            + "\t\"isSynchronousLoading\": true,\n"
            + "\t\"er\": null,\n"
            + "\t\"arValues\": [],\n"
            + "\t\"validationInfo\": {\n"
            + "\t\t\"status\": \"NONE\",\n"
            + "\t\t\"errorDescription\": null\n"
            + "\t},\n"
            + "\t\"bvLink\": null,\n"
            + "\t\"name\": \"param1\",\n"
            + "\t\"path\": \"%3$s\",\n"
            + "\t\"errors\": \"\",\n"
            + "\t\"componentName\": null\n"
            + "}";

    public static final String COMMON_PARAMETER_PARAM_TYPE_WITHOUT_VALIDATION = "{\n"
            + "    \"page\": null,\n"
            + "    \"tab\": null,\n"
            + "    \"group\": null,\n"
            + "    \"parameterConfig\": {\n"
            + "        \"name\": \"testCommon1\",\n"
            + "        \"displayType\": \"PARAM\",\n"
            + "        \"dataSource\": {\n"
            + "            \"system\": \"Business Solution\",\n"
            + "            \"connection\": \"DB\",\n"
            + "            \"engineType\": \"SQL\",\n"
            + "            \"script\": \"\",\n"
            + "            \"settings\": [\n"
            + "                {\n"
            + "                    \"className\": \"LogCollectorSettings\","
            + "                    \"configurations\": [],\n"
            + "                    \"parameters\": {\n"
            + "                        \"searchText\": null,\n"
            + "                        \"graylogSearchText\": null,\n"
            + "                        \"lines\": 0,\n"
            + "                        \"minutes\": 0,\n"
            + "                        \"query\": null,\n"
            + "                        \"readOnlyMode\": false,\n"
            + "                        \"searchPerOneDay\": false,\n"
            + "                        \"searchStrategy\": null,\n"
            + "                        \"previewParameters\": null,\n"
            + "                        \"isLogMessageColumnShowed\": true,\n"
            + "                        \"regexp\": false\n"
            + "                    }\n"
            + "                }\n"
            + "            ]\n"
            + "        },\n"
            + "        \"logsSource\": {\n"
            + "            \"components\": [],\n"
            + "            \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "            \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "        },\n"
            + "        \"er\": {\n"
            + "            \"type\": \"NONE\",\n"
            + "            \"value\": null,\n"
            + "            \"tableValidations\": [],\n"
            + "            \"dataSource\": {\n"
            + "                \"system\": \"\",\n"
            + "                \"connection\": \"\",\n"
            + "                \"engineType\": null,\n"
            + "                \"script\": \"\",\n"
            + "                \"settings\": [\n"
            + "                    {\n"
            + "                        \"className\": \"LogCollectorSettings\","
            + "                        \"configurations\": [],\n"
            + "                        \"parameters\": {\n"
            + "                            \"searchText\": null,\n"
            + "                            \"graylogSearchText\": null,\n"
            + "                            \"lines\": 0,\n"
            + "                            \"minutes\": 0,\n"
            + "                            \"query\": null,\n"
            + "                            \"readOnlyMode\": false,\n"
            + "                            \"searchPerOneDay\": false,\n"
            + "                            \"searchStrategy\": null,\n"
            + "                            \"previewParameters\": null,\n"
            + "                            \"isLogMessageColumnShowed\": true,\n"
            + "                            \"regexp\": false\n"
            + "                        }\n"
            + "                    }\n"
            + "                ]\n"
            + "            },\n"
            + "            \"tableValidationSettings\": {\n"
            + "                \"keyColumns\": [],\n"
            + "                \"groupingColumns\": []\n"
            + "            },\n"
            + "            \"bulkValidatorValidation\": {\n"
            + "                \"validationColumn\": \"\",\n"
            + "                \"validationObjectName\": \"\",\n"
            + "                \"isManualValidation\": false,\n"
            + "                \"validationItem\": [\n"
            + "                    {\n"
            + "                        \"validationColumn\": \"\",\n"
            + "                        \"validationObjectName\": \"\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"testCaseIds\": []\n"
            + "            }\n"
            + "        },\n"
            + "        \"additionalSources\": [],\n"
            + "        \"isPreconfigured\": false,\n"
            + "        \"component\": null\n"
            + "    },\n"
            + "    \"isSynchronousLoading\": false,\n"
            + "    \"er\": null,\n"
            + "    \"arValues\": [],\n"
            + "    \"validationInfo\": {\n"
            + "        \"status\": \"NONE\",\n"
            + "        \"errorDescription\": null\n"
            + "    },\n"
            + "    \"bvLink\": null,\n"
            + "    \"name\": \"testCommon1\",\n"
            + "    \"path\": \"null_null_null_testCommon1\",\n"
            + "    \"componentName\": null,\n"
            + "    \"errors\": \"\"\n"
            + "}";

    public static final String COMMON_PARAMETER_LINK_TYPE_WITHOUT_VALIDATION = "{\n"
            + "    \"page\": null,\n"
            + "    \"tab\": null,\n"
            + "    \"group\": null,\n"
            + "    \"parameterConfig\": {\n"
            + "        \"name\": \"testCommon3\",\n"
            + "        \"displayType\": \"LINK\",\n"
            + "        \"dataSource\": {\n"
            + "            \"system\": \"Business Solution\",\n"
            + "            \"connection\": \"DB\",\n"
            + "            \"engineType\": \"SQL\",\n"
            + "            \"script\": \"\",\n"
            + "            \"settings\": []\n"
            + "        },\n"
            + "        \"logsSource\": {\n"
            + "            \"components\": [],\n"
            + "            \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "            \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "        },\n"
            + "        \"er\": {\n"
            + "            \"type\": \"NONE\",\n"
            + "            \"value\": null,\n"
            + "            \"tableValidations\": [],\n"
            + "            \"dataSource\": {\n"
            + "                \"system\": \"\",\n"
            + "                \"connection\": \"\",\n"
            + "                \"engineType\": null,\n"
            + "                \"script\": \"\",\n"
            + "                \"settings\": []\n"
            + "            },\n"
            + "            \"tableValidationSettings\": {\n"
            + "                \"keyColumns\": [],\n"
            + "                \"groupingColumns\": []\n"
            + "            },\n"
            + "            \"bulkValidatorValidation\": {\n"
            + "                \"validationColumn\": \"\",\n"
            + "                \"validationObjectName\": \"\",\n"
            + "                \"isManualValidation\": false,\n"
            + "                \"validationItem\": [\n"
            + "                    {\n"
            + "                        \"validationColumn\": \"\",\n"
            + "                        \"validationObjectName\": \"\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"testCaseIds\": []\n"
            + "            }\n"
            + "        },\n"
            + "        \"additionalSources\": [],\n"
            + "        \"isPreconfigured\": false,\n"
            + "        \"component\": null\n"
            + "    },\n"
            + "    \"isSynchronousLoading\": false,\n"
            + "    \"er\": null,\n"
            + "    \"arValues\": [],\n"
            + "    \"validationInfo\": {\n"
            + "        \"status\": \"NONE\",\n"
            + "        \"errorDescription\": null\n"
            + "    },\n"
            + "    \"bvLink\": null,\n"
            + "    \"name\": \"testCommon3\",\n"
            + "    \"path\": \"null_null_null_testCommon3\",\n"
            + "    \"componentName\": null,\n"
            + "    \"errors\": \"\"\n"
            + "}";

    public static final String COMMON_PARAMETER_PARAM_TYPE_WITH_VALIDATION = "{\n"
            + "    \"page\": null,\n"
            + "    \"tab\": null,\n"
            + "    \"group\": null,\n"
            + "    \"parameterConfig\": {\n"
            + "        \"name\": \"testCommon2\",\n"
            + "        \"displayType\": \"PARAM\",\n"
            + "        \"dataSource\": {\n"
            + "            \"system\": \"Business Solution\",\n"
            + "            \"connection\": \"DB\",\n"
            + "            \"engineType\": \"SQL\",\n"
            + "            \"script\": \"\",\n"
            + "            \"settings\": [\n"
            + "                {\n"
            + "                    \"className\": \"LogCollectorSettings\","
            + "                    \"configurations\": [],\n"
            + "                    \"parameters\": {\n"
            + "                        \"searchText\": null,\n"
            + "                        \"graylogSearchText\": null,\n"
            + "                        \"lines\": 0,\n"
            + "                        \"minutes\": 0,\n"
            + "                        \"query\": null,\n"
            + "                        \"readOnlyMode\": false,\n"
            + "                        \"searchPerOneDay\": false,\n"
            + "                        \"searchStrategy\": null,\n"
            + "                        \"previewParameters\": null,\n"
            + "                        \"isLogMessageColumnShowed\": true,\n"
            + "                        \"regexp\": false\n"
            + "                    }\n"
            + "                }\n"
            + "            ]\n"
            + "        },\n"
            + "        \"logsSource\": {\n"
            + "            \"components\": [],\n"
            + "            \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "            \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "        },\n"
            + "        \"er\": {\n"
            + "            \"type\": \"CUSTOM\",\n"
            + "            \"value\": null,\n"
            + "            \"tableValidations\": [],\n"
            + "            \"dataSource\": {\n"
            + "                \"system\": \"Business Solution\",\n"
            + "                \"connection\": \"DB\",\n"
            + "                \"engineType\": \"SQL\",\n"
            + "                \"script\": \"\",\n"
            + "                \"settings\": [\n"
            + "                    {\n"
            + "                        \"className\": \"LogCollectorSettings\","
            + "                        \"configurations\": [],\n"
            + "                        \"parameters\": {\n"
            + "                            \"searchText\": null,\n"
            + "                            \"graylogSearchText\": null,\n"
            + "                            \"lines\": 0,\n"
            + "                            \"minutes\": 0,\n"
            + "                            \"query\": null,\n"
            + "                            \"readOnlyMode\": false,\n"
            + "                            \"searchPerOneDay\": false,\n"
            + "                            \"searchStrategy\": null,\n"
            + "                            \"previewParameters\": null,\n"
            + "                            \"isLogMessageColumnShowed\": true,\n"
            + "                            \"regexp\": false\n"
            + "                        }\n"
            + "                    }\n"
            + "                ]\n"
            + "            },\n"
            + "            \"tableValidationSettings\": {\n"
            + "                \"keyColumns\": [],\n"
            + "                \"groupingColumns\": []\n"
            + "            },\n"
            + "            \"bulkValidatorValidation\": {\n"
            + "                \"validationColumn\": \"\",\n"
            + "                \"validationObjectName\": \"\",\n"
            + "                \"isManualValidation\": false,\n"
            + "                \"validationItem\": [\n"
            + "                    {\n"
            + "                        \"validationColumn\": \"\",\n"
            + "                        \"validationObjectName\": \"\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"testCaseIds\": []\n"
            + "            }\n"
            + "        },\n"
            + "        \"additionalSources\": [],\n"
            + "        \"isPreconfigured\": false,\n"
            + "        \"component\": null\n"
            + "    },\n"
            + "    \"isSynchronousLoading\": false,\n"
            + "    \"er\": null,\n"
            + "    \"arValues\": [],\n"
            + "    \"validationInfo\": {\n"
            + "        \"status\": \"PASSED\",\n"
            + "        \"errorDescription\": null\n"
            + "    },\n"
            + "    \"bvLink\": null,\n"
            + "    \"name\": \"testCommon2\",\n"
            + "    \"path\": \"null_null_null_testCommon2\",\n"
            + "    \"componentName\": null,\n"
            + "    \"errors\": \"\"\n"
            + "}";

    public static final String COMMON_PARAMETER_LINK_TYPE_WITH_VALIDATION = "{\n"
            + "    \"page\": null,\n"
            + "    \"tab\": null,\n"
            + "    \"group\": null,\n"
            + "    \"parameterConfig\": {\n"
            + "        \"name\": \"testCommon4\",\n"
            + "        \"displayType\": \"LINK\",\n"
            + "        \"dataSource\": {\n"
            + "            \"system\": \"Business Solution\",\n"
            + "            \"connection\": \"DB\",\n"
            + "            \"engineType\": \"SQL\",\n"
            + "            \"script\": \"\",\n"
            + "            \"settings\": []\n"
            + "        },\n"
            + "        \"logsSource\": {\n"
            + "            \"components\": [],\n"
            + "            \"graylogSearchText\": \"context: ( ${Sales_Order_ID} OR ${Customer_ID} )\",\n"
            + "            \"fileBasedSearchText\": \"(${Sales_Order_ID}|${Customer_ID})\"\n"
            + "        },\n"
            + "        \"er\": {\n"
            + "            \"type\": \"CUSTOM\",\n"
            + "            \"value\": null,\n"
            + "            \"tableValidations\": [],\n"
            + "            \"dataSource\": {\n"
            + "                \"system\": \"Business Solution\",\n"
            + "                \"connection\": \"DB\",\n"
            + "                \"engineType\": \"SQL\",\n"
            + "                \"script\": \"\",\n"
            + "                \"settings\": []\n"
            + "            },\n"
            + "            \"tableValidationSettings\": {\n"
            + "                \"keyColumns\": [],\n"
            + "                \"groupingColumns\": []\n"
            + "            },\n"
            + "            \"bulkValidatorValidation\": {\n"
            + "                \"validationColumn\": \"\",\n"
            + "                \"validationObjectName\": \"\",\n"
            + "                \"isManualValidation\": false,\n"
            + "                \"validationItem\": [\n"
            + "                    {\n"
            + "                        \"validationColumn\": \"\",\n"
            + "                        \"validationObjectName\": \"\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"testCaseIds\": []\n"
            + "            }\n"
            + "        },\n"
            + "        \"additionalSources\": [],\n"
            + "        \"isPreconfigured\": false,\n"
            + "        \"component\": null\n"
            + "    },\n"
            + "    \"isSynchronousLoading\": false,\n"
            + "    \"er\": null,\n"
            + "    \"arValues\": [],\n"
            + "    \"validationInfo\": {\n"
            + "        \"status\": \"FAILED\",\n"
            + "        \"errorDescription\": null\n"
            + "    },\n"
            + "    \"bvLink\": null,\n"
            + "    \"name\": \"testCommon4\",\n"
            + "    \"path\": \"null_null_null_testCommon4\",\n"
            + "    \"componentName\": null,\n"
            + "    \"errors\": \"\"\n"
            + "}";

    public static String getIntegrationLogPotSessionParameterWithValidationBeforeProcessing(String pageName,
                                                                                            String configurationId,
                                                                                            boolean isSynchronousLoading) {
        return String.format(INTEGRATION_LOG_POT_SESSION_PARAMETER_WITH_VALIDATION_BEFORE_PROCESSING, pageName,
                configurationId, isSynchronousLoading);
    }

    public static String getIntegrationLogPotSessionParameterWithoutValidationBeforeProcessing(String pageName,
                                                                                               String configurationId,
                                                                                               boolean isSynchronousLoading) {
        return String.format(INTEGRATION_LOG_POT_SESSION_PARAMETER_WITHOUT_VALIDATION_BEFORE_PROCESSING, pageName,
                configurationId, isSynchronousLoading);
    }

    public static String getLogCollectorErrorResponseBody(String errorMessage, String endpoint) {
        return String.format(LOG_COLLECTOR_ERROR_RESPONSE_BODY_DEFAULT, errorMessage, endpoint);
    }

    public static String getLogCollectorRegisterSearchResponseDefault(String searchId, String componentId,
                                                                      String errorCode) {
        return String.format(LOG_COLLECTOR_REGISTER_SEARCH_RESPONSE_DEFAULT, searchId, componentId, errorCode);
    }

    public static final String INTEGRATION_LOG_PARAMETER_ERROR_VALUE_OBJECT_GET_SEARCH_RESULTS_DEFAULT_MESSAGE =
            "Could not convert search result from LogCollector to LogCollectorValueObject. Error message: "
                    + "Failed to received search results with id: %s from LogCollector";

    public static String getIntegrationLogParameterErrorValueObjectForRegisterSearch(String configurationId,
                                                                                     String searchQueryType,
                                                                                     String requestId) {
        return String.format(INTEGRATION_LOG_PARAMETER_ERROR_VALUE_OBJECT_REGISTER_SEARCH_DEFAULT_MESSAGE,
                configurationId, searchQueryType, requestId);
    }

    public static String getIntegrationLogParameterErrorValueObjectForGetSearchResult(String searchId) {
        return String.format(INTEGRATION_LOG_PARAMETER_ERROR_VALUE_OBJECT_GET_SEARCH_RESULTS_DEFAULT_MESSAGE, searchId);
    }
}
