# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is provided "AS IS", without warranties
# or conditions of any kind, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.1
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: //localhost:8080/
tags:
  - name: key-parameters-controller
    description: Key Parameters Controller
paths:
  /api/svp/project/{projectId}/key-parameters:
    post:
      tags:
        - key-parameters-controller
      summary: getKeyParameters
      operationId: getKeyParameters
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          schema:
            type: string
      requestBody:
        description: keyParameters doesn't need
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeyParameterRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
      deprecated: false
  /api/svp/project/{projectId}/key-parameters/update:
    post:
      tags:
        - key-parameters-controller
      summary: updateKeyParameters
      operationId: updateKeyParameters
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          schema:
            type: string
      requestBody:
        description: KeyParameterRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeyParameterRequest'
        required: true
      responses:
        200:
          description: OK
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
      deprecated: false
      x-codegen-request-body-name: keyParameters
components:
  schemas:
    KeyParameterRequest:
      title: KeyParameterRequest
      type: object
      properties:
        keyParameters:
          type: array
          items:
            type: string
        folder:
          type: string
