---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
  selector:
    name: '{{ .Values.SERVICE_NAME }}'
  type: NodePort

